language: python
python:
 
  - "3.6"      # current default Python on Travis CI
 
# command to install dependencies

services:
  - docker
before_script: pip install docker-compose
# command to run tests
script:
  - docker-compose run app sh -c "python manage.py test && flake8"